// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/protocol/provider/provider.proto

package providerpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TouchEvent_Action int32

const (
	TouchEvent_DOWN TouchEvent_Action = 0
	TouchEvent_MOVE TouchEvent_Action = 1
	TouchEvent_UP   TouchEvent_Action = 2
)

// Enum value maps for TouchEvent_Action.
var (
	TouchEvent_Action_name = map[int32]string{
		0: "DOWN",
		1: "MOVE",
		2: "UP",
	}
	TouchEvent_Action_value = map[string]int32{
		"DOWN": 0,
		"MOVE": 1,
		"UP":   2,
	}
)

func (x TouchEvent_Action) Enum() *TouchEvent_Action {
	p := new(TouchEvent_Action)
	*p = x
	return p
}

func (x TouchEvent_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TouchEvent_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_provider_provider_proto_enumTypes[0].Descriptor()
}

func (TouchEvent_Action) Type() protoreflect.EnumType {
	return &file_pkg_protocol_provider_provider_proto_enumTypes[0]
}

func (x TouchEvent_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TouchEvent_Action.Descriptor instead.
func (TouchEvent_Action) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{13, 0}
}

type KeyEvent_Action int32

const (
	KeyEvent_DOWN KeyEvent_Action = 0
	KeyEvent_UP   KeyEvent_Action = 1
)

// Enum value maps for KeyEvent_Action.
var (
	KeyEvent_Action_name = map[int32]string{
		0: "DOWN",
		1: "UP",
	}
	KeyEvent_Action_value = map[string]int32{
		"DOWN": 0,
		"UP":   1,
	}
)

func (x KeyEvent_Action) Enum() *KeyEvent_Action {
	p := new(KeyEvent_Action)
	*p = x
	return p
}

func (x KeyEvent_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyEvent_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_provider_provider_proto_enumTypes[1].Descriptor()
}

func (KeyEvent_Action) Type() protoreflect.EnumType {
	return &file_pkg_protocol_provider_provider_proto_enumTypes[1]
}

func (x KeyEvent_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyEvent_Action.Descriptor instead.
func (KeyEvent_Action) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{14, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{2}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildDate     string                 `protobuf:"bytes,2,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{4}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceProto         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceProto {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Serial         string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer   string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	AndroidVersion string                 `protobuf:"bytes,4,opt,name=android_version,json=androidVersion,proto3" json:"android_version,omitempty"`
	SdkVersion     int32                  `protobuf:"varint,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	CpuAbi         string                 `protobuf:"bytes,6,opt,name=cpu_abi,json=cpuAbi,proto3" json:"cpu_abi,omitempty"`
	RamMb          int64                  `protobuf:"varint,7,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	StorageMb      int64                  `protobuf:"varint,8,opt,name=storage_mb,json=storageMb,proto3" json:"storage_mb,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // idle | claimed | busy | offline
	Port           int32                  `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`   // stream port
	BatteryLevel   int32                  `protobuf:"varint,11,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	IpAddress      string                 `protobuf:"bytes,12,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ConnectedAt    *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceProto) Reset() {
	*x = DeviceProto{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProto) ProtoMessage() {}

func (x *DeviceProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProto.ProtoReflect.Descriptor instead.
func (*DeviceProto) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceProto) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceProto) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceProto) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DeviceProto) GetAndroidVersion() string {
	if x != nil {
		return x.AndroidVersion
	}
	return ""
}

func (x *DeviceProto) GetSdkVersion() int32 {
	if x != nil {
		return x.SdkVersion
	}
	return 0
}

func (x *DeviceProto) GetCpuAbi() string {
	if x != nil {
		return x.CpuAbi
	}
	return ""
}

func (x *DeviceProto) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *DeviceProto) GetStorageMb() int64 {
	if x != nil {
		return x.StorageMb
	}
	return 0
}

func (x *DeviceProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceProto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeviceProto) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *DeviceProto) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DeviceProto) GetConnectedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type ClaimDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	ClaimedBy     string                 `protobuf:"bytes,2,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"` // email or user identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimDeviceRequest) Reset() {
	*x = ClaimDeviceRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDeviceRequest) ProtoMessage() {}

func (x *ClaimDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDeviceRequest.ProtoReflect.Descriptor instead.
func (*ClaimDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimDeviceRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *ClaimDeviceRequest) GetClaimedBy() string {
	if x != nil {
		return x.ClaimedBy
	}
	return ""
}

type ClaimDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"` // stream port allocated
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimDeviceResponse) Reset() {
	*x = ClaimDeviceResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDeviceResponse) ProtoMessage() {}

func (x *ClaimDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDeviceResponse.ProtoReflect.Descriptor instead.
func (*ClaimDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimDeviceResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClaimDeviceResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClaimDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceRequest) Reset() {
	*x = ReleaseDeviceRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceRequest) ProtoMessage() {}

func (x *ReleaseDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseDeviceRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type ReleaseDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceResponse) Reset() {
	*x = ReleaseDeviceResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceResponse) ProtoMessage() {}

func (x *ReleaseDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Serial string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ControlRequest_Touch
	//	*ControlRequest_Key
	//	*ControlRequest_Text
	//	*ControlRequest_Rotate
	//	*ControlRequest_Shell
	Event         isControlRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{11}
}

func (x *ControlRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *ControlRequest) GetEvent() isControlRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ControlRequest) GetTouch() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*ControlRequest_Touch); ok {
			return x.Touch
		}
	}
	return nil
}

func (x *ControlRequest) GetKey() *KeyEvent {
	if x != nil {
		if x, ok := x.Event.(*ControlRequest_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *ControlRequest) GetText() *TextEvent {
	if x != nil {
		if x, ok := x.Event.(*ControlRequest_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ControlRequest) GetRotate() *RotateEvent {
	if x != nil {
		if x, ok := x.Event.(*ControlRequest_Rotate); ok {
			return x.Rotate
		}
	}
	return nil
}

func (x *ControlRequest) GetShell() *ShellCommandRequest {
	if x != nil {
		if x, ok := x.Event.(*ControlRequest_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

type isControlRequest_Event interface {
	isControlRequest_Event()
}

type ControlRequest_Touch struct {
	Touch *TouchEvent `protobuf:"bytes,2,opt,name=touch,proto3,oneof"`
}

type ControlRequest_Key struct {
	Key *KeyEvent `protobuf:"bytes,3,opt,name=key,proto3,oneof"`
}

type ControlRequest_Text struct {
	Text *TextEvent `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type ControlRequest_Rotate struct {
	Rotate *RotateEvent `protobuf:"bytes,5,opt,name=rotate,proto3,oneof"`
}

type ControlRequest_Shell struct {
	Shell *ShellCommandRequest `protobuf:"bytes,6,opt,name=shell,proto3,oneof"`
}

func (*ControlRequest_Touch) isControlRequest_Event() {}

func (*ControlRequest_Key) isControlRequest_Event() {}

func (*ControlRequest_Text) isControlRequest_Event() {}

func (*ControlRequest_Rotate) isControlRequest_Event() {}

func (*ControlRequest_Shell) isControlRequest_Event() {}

type ControlResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ControlResponse_ShellResponse
	Response      isControlResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{12}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetResponse() isControlResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ControlResponse) GetShellResponse() *ShellCommandResponse {
	if x != nil {
		if x, ok := x.Response.(*ControlResponse_ShellResponse); ok {
			return x.ShellResponse
		}
	}
	return nil
}

type isControlResponse_Response interface {
	isControlResponse_Response()
}

type ControlResponse_ShellResponse struct {
	ShellResponse *ShellCommandResponse `protobuf:"bytes,3,opt,name=shell_response,json=shellResponse,proto3,oneof"`
}

func (*ControlResponse_ShellResponse) isControlResponse_Response() {}

type TouchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        TouchEvent_Action      `protobuf:"varint,1,opt,name=action,proto3,enum=provider.TouchEvent_Action" json:"action,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PointerId     int32                  `protobuf:"varint,4,opt,name=pointer_id,json=pointerId,proto3" json:"pointer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{13}
}

func (x *TouchEvent) GetAction() TouchEvent_Action {
	if x != nil {
		return x.Action
	}
	return TouchEvent_DOWN
}

func (x *TouchEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TouchEvent) GetPointerId() int32 {
	if x != nil {
		return x.PointerId
	}
	return 0
}

type KeyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        KeyEvent_Action        `protobuf:"varint,1,opt,name=action,proto3,enum=provider.KeyEvent_Action" json:"action,omitempty"`
	KeyCode       int32                  `protobuf:"varint,2,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"` // Android KeyEvent key code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{14}
}

func (x *KeyEvent) GetAction() KeyEvent_Action {
	if x != nil {
		return x.Action
	}
	return KeyEvent_DOWN
}

func (x *KeyEvent) GetKeyCode() int32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{15}
}

func (x *TextEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type RotateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rotation      int32                  `protobuf:"varint,1,opt,name=rotation,proto3" json:"rotation,omitempty"` // 0, 90, 180, 270 degrees
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateEvent) Reset() {
	*x = RotateEvent{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateEvent) ProtoMessage() {}

func (x *RotateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateEvent.ProtoReflect.Descriptor instead.
func (*RotateEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{16}
}

func (x *RotateEvent) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

type ShellCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommandRequest) Reset() {
	*x = ShellCommandRequest{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommandRequest) ProtoMessage() {}

func (x *ShellCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommandRequest.ProtoReflect.Descriptor instead.
func (*ShellCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ShellCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ShellCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommandResponse) Reset() {
	*x = ShellCommandResponse{}
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommandResponse) ProtoMessage() {}

func (x *ShellCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_provider_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommandResponse.ProtoReflect.Descriptor instead.
func (*ShellCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_provider_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ShellCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ShellCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_pkg_protocol_provider_provider_proto protoreflect.FileDescriptor

const file_pkg_protocol_provider_provider_proto_rawDesc = "" +
	"\n" +
	"$pkg/protocol/provider/provider.proto\x12\bprovider\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eVersionRequest\"J\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_date\x18\x02 \x01(\tR\tbuildDate\"\x14\n" +
	"\x12ListDevicesRequest\"F\n" +
	"\x13ListDevicesResponse\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.provider.DeviceProtoR\adevices\"\xa7\x03\n" +
	"\vDeviceProto\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\x12'\n" +
	"\x0fandroid_version\x18\x04 \x01(\tR\x0eandroidVersion\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\x05R\n" +
	"sdkVersion\x12\x17\n" +
	"\acpu_abi\x18\x06 \x01(\tR\x06cpuAbi\x12\x15\n" +
	"\x06ram_mb\x18\a \x01(\x03R\x05ramMb\x12\x1d\n" +
	"\n" +
	"storage_mb\x18\b \x01(\x03R\tstorageMb\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x12\n" +
	"\x04port\x18\n" +
	" \x01(\x05R\x04port\x12#\n" +
	"\rbattery_level\x18\v \x01(\x05R\fbatteryLevel\x12\x1d\n" +
	"\n" +
	"ip_address\x18\f \x01(\tR\tipAddress\x12=\n" +
	"\fconnected_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"K\n" +
	"\x12ClaimDeviceRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"claimed_by\x18\x02 \x01(\tR\tclaimedBy\"|\n" +
	"\x13ClaimDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\".\n" +
	"\x14ReleaseDeviceRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\"K\n" +
	"\x15ReleaseDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9a\x02\n" +
	"\x0eControlRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12,\n" +
	"\x05touch\x18\x02 \x01(\v2\x14.provider.TouchEventH\x00R\x05touch\x12&\n" +
	"\x03key\x18\x03 \x01(\v2\x12.provider.KeyEventH\x00R\x03key\x12)\n" +
	"\x04text\x18\x04 \x01(\v2\x13.provider.TextEventH\x00R\x04text\x12/\n" +
	"\x06rotate\x18\x05 \x01(\v2\x15.provider.RotateEventH\x00R\x06rotate\x125\n" +
	"\x05shell\x18\x06 \x01(\v2\x1d.provider.ShellCommandRequestH\x00R\x05shellB\a\n" +
	"\x05event\"\x9a\x01\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x0eshell_response\x18\x03 \x01(\v2\x1e.provider.ShellCommandResponseH\x00R\rshellResponseB\n" +
	"\n" +
	"\bresponse\"\xa2\x01\n" +
	"\n" +
	"TouchEvent\x123\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1b.provider.TouchEvent.ActionR\x06action\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1d\n" +
	"\n" +
	"pointer_id\x18\x04 \x01(\x05R\tpointerId\"$\n" +
	"\x06Action\x12\b\n" +
	"\x04DOWN\x10\x00\x12\b\n" +
	"\x04MOVE\x10\x01\x12\x06\n" +
	"\x02UP\x10\x02\"t\n" +
	"\bKeyEvent\x121\n" +
	"\x06action\x18\x01 \x01(\x0e2\x19.provider.KeyEvent.ActionR\x06action\x12\x19\n" +
	"\bkey_code\x18\x02 \x01(\x05R\akeyCode\"\x1a\n" +
	"\x06Action\x12\b\n" +
	"\x04DOWN\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\"\x1f\n" +
	"\tTextEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\")\n" +
	"\vRotateEvent\x12\x1a\n" +
	"\brotation\x18\x01 \x01(\x05R\brotation\"/\n" +
	"\x13ShellCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"K\n" +
	"\x14ShellCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode2\xd4\x03\n" +
	"\x0fProviderService\x12J\n" +
	"\vHealthCheck\x12\x1c.provider.HealthCheckRequest\x1a\x1d.provider.HealthCheckResponse\x12A\n" +
	"\n" +
	"GetVersion\x12\x18.provider.VersionRequest\x1a\x19.provider.VersionResponse\x12J\n" +
	"\vListDevices\x12\x1c.provider.ListDevicesRequest\x1a\x1d.provider.ListDevicesResponse\x12J\n" +
	"\vClaimDevice\x12\x1c.provider.ClaimDeviceRequest\x1a\x1d.provider.ClaimDeviceResponse\x12P\n" +
	"\rReleaseDevice\x12\x1e.provider.ReleaseDeviceRequest\x1a\x1f.provider.ReleaseDeviceResponse\x12H\n" +
	"\rControlDevice\x12\x18.provider.ControlRequest\x1a\x19.provider.ControlResponse(\x010\x01B3Z1protean-provider/pkg/protocol/provider;providerpbb\x06proto3"

var (
	file_pkg_protocol_provider_provider_proto_rawDescOnce sync.Once
	file_pkg_protocol_provider_provider_proto_rawDescData []byte
)

func file_pkg_protocol_provider_provider_proto_rawDescGZIP() []byte {
	file_pkg_protocol_provider_provider_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_provider_provider_proto_rawDesc), len(file_pkg_protocol_provider_provider_proto_rawDesc)))
	})
	return file_pkg_protocol_provider_provider_proto_rawDescData
}

var file_pkg_protocol_provider_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_protocol_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pkg_protocol_provider_provider_proto_goTypes = []any{
	(TouchEvent_Action)(0),        // 0: provider.TouchEvent.Action
	(KeyEvent_Action)(0),          // 1: provider.KeyEvent.Action
	(*HealthCheckRequest)(nil),    // 2: provider.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 3: provider.HealthCheckResponse
	(*VersionRequest)(nil),        // 4: provider.VersionRequest
	(*VersionResponse)(nil),       // 5: provider.VersionResponse
	(*ListDevicesRequest)(nil),    // 6: provider.ListDevicesRequest
	(*ListDevicesResponse)(nil),   // 7: provider.ListDevicesResponse
	(*DeviceProto)(nil),           // 8: provider.DeviceProto
	(*ClaimDeviceRequest)(nil),    // 9: provider.ClaimDeviceRequest
	(*ClaimDeviceResponse)(nil),   // 10: provider.ClaimDeviceResponse
	(*ReleaseDeviceRequest)(nil),  // 11: provider.ReleaseDeviceRequest
	(*ReleaseDeviceResponse)(nil), // 12: provider.ReleaseDeviceResponse
	(*ControlRequest)(nil),        // 13: provider.ControlRequest
	(*ControlResponse)(nil),       // 14: provider.ControlResponse
	(*TouchEvent)(nil),            // 15: provider.TouchEvent
	(*KeyEvent)(nil),              // 16: provider.KeyEvent
	(*TextEvent)(nil),             // 17: provider.TextEvent
	(*RotateEvent)(nil),           // 18: provider.RotateEvent
	(*ShellCommandRequest)(nil),   // 19: provider.ShellCommandRequest
	(*ShellCommandResponse)(nil),  // 20: provider.ShellCommandResponse
	(*timestamp.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_pkg_protocol_provider_provider_proto_depIdxs = []int32{
	8,  // 0: provider.ListDevicesResponse.devices:type_name -> provider.DeviceProto
	21, // 1: provider.DeviceProto.connected_at:type_name -> google.protobuf.Timestamp
	15, // 2: provider.ControlRequest.touch:type_name -> provider.TouchEvent
	16, // 3: provider.ControlRequest.key:type_name -> provider.KeyEvent
	17, // 4: provider.ControlRequest.text:type_name -> provider.TextEvent
	18, // 5: provider.ControlRequest.rotate:type_name -> provider.RotateEvent
	19, // 6: provider.ControlRequest.shell:type_name -> provider.ShellCommandRequest
	20, // 7: provider.ControlResponse.shell_response:type_name -> provider.ShellCommandResponse
	0,  // 8: provider.TouchEvent.action:type_name -> provider.TouchEvent.Action
	1,  // 9: provider.KeyEvent.action:type_name -> provider.KeyEvent.Action
	2,  // 10: provider.ProviderService.HealthCheck:input_type -> provider.HealthCheckRequest
	4,  // 11: provider.ProviderService.GetVersion:input_type -> provider.VersionRequest
	6,  // 12: provider.ProviderService.ListDevices:input_type -> provider.ListDevicesRequest
	9,  // 13: provider.ProviderService.ClaimDevice:input_type -> provider.ClaimDeviceRequest
	11, // 14: provider.ProviderService.ReleaseDevice:input_type -> provider.ReleaseDeviceRequest
	13, // 15: provider.ProviderService.ControlDevice:input_type -> provider.ControlRequest
	3,  // 16: provider.ProviderService.HealthCheck:output_type -> provider.HealthCheckResponse
	5,  // 17: provider.ProviderService.GetVersion:output_type -> provider.VersionResponse
	7,  // 18: provider.ProviderService.ListDevices:output_type -> provider.ListDevicesResponse
	10, // 19: provider.ProviderService.ClaimDevice:output_type -> provider.ClaimDeviceResponse
	12, // 20: provider.ProviderService.ReleaseDevice:output_type -> provider.ReleaseDeviceResponse
	14, // 21: provider.ProviderService.ControlDevice:output_type -> provider.ControlResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_protocol_provider_provider_proto_init() }
func file_pkg_protocol_provider_provider_proto_init() {
	if File_pkg_protocol_provider_provider_proto != nil {
		return
	}
	file_pkg_protocol_provider_provider_proto_msgTypes[11].OneofWrappers = []any{
		(*ControlRequest_Touch)(nil),
		(*ControlRequest_Key)(nil),
		(*ControlRequest_Text)(nil),
		(*ControlRequest_Rotate)(nil),
		(*ControlRequest_Shell)(nil),
	}
	file_pkg_protocol_provider_provider_proto_msgTypes[12].OneofWrappers = []any{
		(*ControlResponse_ShellResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_provider_provider_proto_rawDesc), len(file_pkg_protocol_provider_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_provider_provider_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_provider_provider_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_provider_provider_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_provider_provider_proto_msgTypes,
	}.Build()
	File_pkg_protocol_provider_provider_proto = out.File
	file_pkg_protocol_provider_provider_proto_goTypes = nil
	file_pkg_protocol_provider_provider_proto_depIdxs = nil
}
