// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: pkg/protocol/provider/provider.proto

package providerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_HealthCheck_FullMethodName   = "/provider.ProviderService/HealthCheck"
	ProviderService_GetVersion_FullMethodName    = "/provider.ProviderService/GetVersion"
	ProviderService_ListDevices_FullMethodName   = "/provider.ProviderService/ListDevices"
	ProviderService_ClaimDevice_FullMethodName   = "/provider.ProviderService/ClaimDevice"
	ProviderService_ReleaseDevice_FullMethodName = "/provider.ProviderService/ReleaseDevice"
	ProviderService_ControlDevice_FullMethodName = "/provider.ProviderService/ControlDevice"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// ProviderService — the provider exposes this service.
// The coordinator or user client is the client; the provider is the server.
// ─────────────────────────────────────────────────────────────────────────────
type ProviderServiceClient interface {
	// HealthCheck reports the status of the provider.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetVersion returns the provider build version info.
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// ListDevices returns all devices currently connected to this provider.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// ClaimDevice transitions a device to the claimed state and starts a session.
	ClaimDevice(ctx context.Context, in *ClaimDeviceRequest, opts ...grpc.CallOption) (*ClaimDeviceResponse, error)
	// ReleaseDevice transitions a claimed device back to the idle state.
	ReleaseDevice(ctx context.Context, in *ReleaseDeviceRequest, opts ...grpc.CallOption) (*ReleaseDeviceResponse, error)
	// ControlDevice opens a bidirectional channel for touch, key, and command events.
	ControlDevice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlRequest, ControlResponse], error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ProviderService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ClaimDevice(ctx context.Context, in *ClaimDeviceRequest, opts ...grpc.CallOption) (*ClaimDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimDeviceResponse)
	err := c.cc.Invoke(ctx, ProviderService_ClaimDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ReleaseDevice(ctx context.Context, in *ReleaseDeviceRequest, opts ...grpc.CallOption) (*ReleaseDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseDeviceResponse)
	err := c.cc.Invoke(ctx, ProviderService_ReleaseDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ControlDevice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlRequest, ControlResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[0], ProviderService_ControlDevice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlRequest, ControlResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_ControlDeviceClient = grpc.BidiStreamingClient[ControlRequest, ControlResponse]

// ProviderServiceServer is the server API for ProviderService service.
// All implementations should embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// ProviderService — the provider exposes this service.
// The coordinator or user client is the client; the provider is the server.
// ─────────────────────────────────────────────────────────────────────────────
type ProviderServiceServer interface {
	// HealthCheck reports the status of the provider.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetVersion returns the provider build version info.
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	// ListDevices returns all devices currently connected to this provider.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// ClaimDevice transitions a device to the claimed state and starts a session.
	ClaimDevice(context.Context, *ClaimDeviceRequest) (*ClaimDeviceResponse, error)
	// ReleaseDevice transitions a claimed device back to the idle state.
	ReleaseDevice(context.Context, *ReleaseDeviceRequest) (*ReleaseDeviceResponse, error)
	// ControlDevice opens a bidirectional channel for touch, key, and command events.
	ControlDevice(grpc.BidiStreamingServer[ControlRequest, ControlResponse]) error
}

// UnimplementedProviderServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedProviderServiceServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedProviderServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedProviderServiceServer) ClaimDevice(context.Context, *ClaimDeviceRequest) (*ClaimDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimDevice not implemented")
}
func (UnimplementedProviderServiceServer) ReleaseDevice(context.Context, *ReleaseDeviceRequest) (*ReleaseDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseDevice not implemented")
}
func (UnimplementedProviderServiceServer) ControlDevice(grpc.BidiStreamingServer[ControlRequest, ControlResponse]) error {
	return status.Error(codes.Unimplemented, "method ControlDevice not implemented")
}
func (UnimplementedProviderServiceServer) testEmbeddedByValue() {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ClaimDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ClaimDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ClaimDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ClaimDevice(ctx, req.(*ClaimDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ReleaseDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ReleaseDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ReleaseDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ReleaseDevice(ctx, req.(*ReleaseDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ControlDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).ControlDevice(&grpc.GenericServerStream[ControlRequest, ControlResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_ControlDeviceServer = grpc.BidiStreamingServer[ControlRequest, ControlResponse]

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provider.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ProviderService_HealthCheck_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ProviderService_GetVersion_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _ProviderService_ListDevices_Handler,
		},
		{
			MethodName: "ClaimDevice",
			Handler:    _ProviderService_ClaimDevice_Handler,
		},
		{
			MethodName: "ReleaseDevice",
			Handler:    _ProviderService_ReleaseDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlDevice",
			Handler:       _ProviderService_ControlDevice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/protocol/provider/provider.proto",
}
