// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/protocol/coordinator/coordinator.proto

package coordinatorpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────────────────────────────────────
// RegisterProvider
// ─────────────────────────────────────────────────────────────────────────────
type RegisterProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	MinPort       int32                  `protobuf:"varint,5,opt,name=min_port,json=minPort,proto3" json:"min_port,omitempty"`
	MaxPort       int32                  `protobuf:"varint,6,opt,name=max_port,json=maxPort,proto3" json:"max_port,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderRequest) Reset() {
	*x = RegisterProviderRequest{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderRequest) ProtoMessage() {}

func (x *RegisterProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterProviderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RegisterProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterProviderRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterProviderRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterProviderRequest) GetMinPort() int32 {
	if x != nil {
		return x.MinPort
	}
	return 0
}

func (x *RegisterProviderRequest) GetMaxPort() int32 {
	if x != nil {
		return x.MaxPort
	}
	return 0
}

func (x *RegisterProviderRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable reason if not accepted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProviderResponse) Reset() {
	*x = RegisterProviderResponse{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProviderResponse) ProtoMessage() {}

func (x *RegisterProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterProviderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProviderResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// RegisterDevice
// ─────────────────────────────────────────────────────────────────────────────
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Android       string                 `protobuf:"bytes,5,opt,name=android,proto3" json:"android,omitempty"`
	Sdk           int32                  `protobuf:"varint,6,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Abi           string                 `protobuf:"bytes,7,opt,name=abi,proto3" json:"abi,omitempty"`
	RamMb         int64                  `protobuf:"varint,8,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	StorageMb     int64                  `protobuf:"varint,9,opt,name=storage_mb,json=storageMb,proto3" json:"storage_mb,omitempty"`
	DisplayWidth  int32                  `protobuf:"varint,10,opt,name=display_width,json=displayWidth,proto3" json:"display_width,omitempty"`
	DisplayHeight int32                  `protobuf:"varint,11,opt,name=display_height,json=displayHeight,proto3" json:"display_height,omitempty"`
	DisplayDpi    int32                  `protobuf:"varint,12,opt,name=display_dpi,json=displayDpi,proto3" json:"display_dpi,omitempty"`
	Battery       int32                  `protobuf:"varint,13,opt,name=battery,proto3" json:"battery,omitempty"`
	WifiSsid      string                 `protobuf:"bytes,14,opt,name=wifi_ssid,json=wifiSsid,proto3" json:"wifi_ssid,omitempty"`
	Ip            string                 `protobuf:"bytes,15,opt,name=ip,proto3" json:"ip,omitempty"`
	ConnectedAt   *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RegisterDeviceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterDeviceRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *RegisterDeviceRequest) GetAndroid() string {
	if x != nil {
		return x.Android
	}
	return ""
}

func (x *RegisterDeviceRequest) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *RegisterDeviceRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *RegisterDeviceRequest) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *RegisterDeviceRequest) GetStorageMb() int64 {
	if x != nil {
		return x.StorageMb
	}
	return 0
}

func (x *RegisterDeviceRequest) GetDisplayWidth() int32 {
	if x != nil {
		return x.DisplayWidth
	}
	return 0
}

func (x *RegisterDeviceRequest) GetDisplayHeight() int32 {
	if x != nil {
		return x.DisplayHeight
	}
	return 0
}

func (x *RegisterDeviceRequest) GetDisplayDpi() int32 {
	if x != nil {
		return x.DisplayDpi
	}
	return 0
}

func (x *RegisterDeviceRequest) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *RegisterDeviceRequest) GetWifiSsid() string {
	if x != nil {
		return x.WifiSsid
	}
	return ""
}

func (x *RegisterDeviceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterDeviceRequest) GetConnectedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeviceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// ReleaseDevice
// ─────────────────────────────────────────────────────────────────────────────
type ReleaseDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceRequest) Reset() {
	*x = ReleaseDeviceRequest{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceRequest) ProtoMessage() {}

func (x *ReleaseDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseDeviceRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ReleaseDeviceRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type ReleaseDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDeviceResponse) Reset() {
	*x = ReleaseDeviceResponse{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDeviceResponse) ProtoMessage() {}

func (x *ReleaseDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDeviceResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseDeviceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ─────────────────────────────────────────────────────────────────────────────
// UpdateDeviceState
// ─────────────────────────────────────────────────────────────────────────────
type UpdateDeviceStateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProviderId            string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Serial                string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Battery               int32                  `protobuf:"varint,3,opt,name=battery,proto3" json:"battery,omitempty"`
	WifiSsid              string                 `protobuf:"bytes,4,opt,name=wifi_ssid,json=wifiSsid,proto3" json:"wifi_ssid,omitempty"`
	FileSystemJson        string                 `protobuf:"bytes,5,opt,name=file_system_json,json=fileSystemJson,proto3" json:"file_system_json,omitempty"`
	InstalledBrowsersJson string                 `protobuf:"bytes,6,opt,name=installed_browsers_json,json=installedBrowsersJson,proto3" json:"installed_browsers_json,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateDeviceStateRequest) Reset() {
	*x = UpdateDeviceStateRequest{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceStateRequest) ProtoMessage() {}

func (x *UpdateDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDeviceStateRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *UpdateDeviceStateRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *UpdateDeviceStateRequest) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *UpdateDeviceStateRequest) GetWifiSsid() string {
	if x != nil {
		return x.WifiSsid
	}
	return ""
}

func (x *UpdateDeviceStateRequest) GetFileSystemJson() string {
	if x != nil {
		return x.FileSystemJson
	}
	return ""
}

func (x *UpdateDeviceStateRequest) GetInstalledBrowsersJson() string {
	if x != nil {
		return x.InstalledBrowsersJson
	}
	return ""
}

type UpdateDeviceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceStateResponse) Reset() {
	*x = UpdateDeviceStateResponse{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceStateResponse) ProtoMessage() {}

func (x *UpdateDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDeviceStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDeviceStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// Heartbeat stream
// ─────────────────────────────────────────────────────────────────────────────
type HeartbeatPing struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProviderId string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	SentAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Snapshot of currently connected device serials.
	DeviceSerials []string `protobuf:"bytes,3,rep,name=device_serials,json=deviceSerials,proto3" json:"device_serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatPing) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *HeartbeatPing) GetSentAt() *timestamp.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *HeartbeatPing) GetDeviceSerials() []string {
	if x != nil {
		return x.DeviceSerials
	}
	return nil
}

type HeartbeatPong struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ReceivedAt *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// Optional command the coordinator wants the provider to act on.
	//
	// Types that are valid to be assigned to Command:
	//
	//	*HeartbeatPong_Reconnect
	//	*HeartbeatPong_Shutdown
	Command       isHeartbeatPong_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatPong) GetReceivedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *HeartbeatPong) GetCommand() isHeartbeatPong_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *HeartbeatPong) GetReconnect() *ReconnectCommand {
	if x != nil {
		if x, ok := x.Command.(*HeartbeatPong_Reconnect); ok {
			return x.Reconnect
		}
	}
	return nil
}

func (x *HeartbeatPong) GetShutdown() *ShutdownCommand {
	if x != nil {
		if x, ok := x.Command.(*HeartbeatPong_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isHeartbeatPong_Command interface {
	isHeartbeatPong_Command()
}

type HeartbeatPong_Reconnect struct {
	Reconnect *ReconnectCommand `protobuf:"bytes,2,opt,name=reconnect,proto3,oneof"`
}

type HeartbeatPong_Shutdown struct {
	Shutdown *ShutdownCommand `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

func (*HeartbeatPong_Reconnect) isHeartbeatPong_Command() {}

func (*HeartbeatPong_Shutdown) isHeartbeatPong_Command() {}

type ReconnectCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectCommand) Reset() {
	*x = ReconnectCommand{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectCommand) ProtoMessage() {}

func (x *ReconnectCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectCommand.ProtoReflect.Descriptor instead.
func (*ReconnectCommand) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *ReconnectCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShutdownCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownCommand) Reset() {
	*x = ShutdownCommand{}
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownCommand) ProtoMessage() {}

func (x *ShutdownCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_coordinator_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownCommand.ProtoReflect.Descriptor instead.
func (*ShutdownCommand) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *ShutdownCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_protocol_coordinator_coordinator_proto protoreflect.FileDescriptor

const file_pkg_protocol_coordinator_coordinator_proto_rawDesc = "" +
	"\n" +
	"*pkg/protocol/coordinator/coordinator.proto\x12\vcoordinator\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\x17RegisterProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x19\n" +
	"\bmin_port\x18\x05 \x01(\x05R\aminPort\x12\x19\n" +
	"\bmax_port\x18\x06 \x01(\x05R\amaxPort\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"P\n" +
	"\x18RegisterProviderResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf1\x03\n" +
	"\x15RegisterDeviceRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x18\n" +
	"\aandroid\x18\x05 \x01(\tR\aandroid\x12\x10\n" +
	"\x03sdk\x18\x06 \x01(\x05R\x03sdk\x12\x10\n" +
	"\x03abi\x18\a \x01(\tR\x03abi\x12\x15\n" +
	"\x06ram_mb\x18\b \x01(\x03R\x05ramMb\x12\x1d\n" +
	"\n" +
	"storage_mb\x18\t \x01(\x03R\tstorageMb\x12#\n" +
	"\rdisplay_width\x18\n" +
	" \x01(\x05R\fdisplayWidth\x12%\n" +
	"\x0edisplay_height\x18\v \x01(\x05R\rdisplayHeight\x12\x1f\n" +
	"\vdisplay_dpi\x18\f \x01(\x05R\n" +
	"displayDpi\x12\x18\n" +
	"\abattery\x18\r \x01(\x05R\abattery\x12\x1b\n" +
	"\twifi_ssid\x18\x0e \x01(\tR\bwifiSsid\x12\x0e\n" +
	"\x02ip\x18\x0f \x01(\tR\x02ip\x12=\n" +
	"\fconnected_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"N\n" +
	"\x16RegisterDeviceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x14ReleaseDeviceRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\"'\n" +
	"\x15ReleaseDeviceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xec\x01\n" +
	"\x18UpdateDeviceStateRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\abattery\x18\x03 \x01(\x05R\abattery\x12\x1b\n" +
	"\twifi_ssid\x18\x04 \x01(\tR\bwifiSsid\x12(\n" +
	"\x10file_system_json\x18\x05 \x01(\tR\x0efileSystemJson\x126\n" +
	"\x17installed_browsers_json\x18\x06 \x01(\tR\x15installedBrowsersJson\"O\n" +
	"\x19UpdateDeviceStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8c\x01\n" +
	"\rHeartbeatPing\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12%\n" +
	"\x0edevice_serials\x18\x03 \x03(\tR\rdeviceSerials\"\xd2\x01\n" +
	"\rHeartbeatPong\x12;\n" +
	"\vreceived_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12=\n" +
	"\treconnect\x18\x02 \x01(\v2\x1d.coordinator.ReconnectCommandH\x00R\treconnect\x12:\n" +
	"\bshutdown\x18\x03 \x01(\v2\x1c.coordinator.ShutdownCommandH\x00R\bshutdownB\t\n" +
	"\acommand\"*\n" +
	"\x10ReconnectCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\")\n" +
	"\x0fShutdownCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xd5\x03\n" +
	"\x12CoordinatorService\x12_\n" +
	"\x10RegisterProvider\x12$.coordinator.RegisterProviderRequest\x1a%.coordinator.RegisterProviderResponse\x12Y\n" +
	"\x0eRegisterDevice\x12\".coordinator.RegisterDeviceRequest\x1a#.coordinator.RegisterDeviceResponse\x12V\n" +
	"\rReleaseDevice\x12!.coordinator.ReleaseDeviceRequest\x1a\".coordinator.ReleaseDeviceResponse\x12G\n" +
	"\tHeartbeat\x12\x1a.coordinator.HeartbeatPing\x1a\x1a.coordinator.HeartbeatPong(\x010\x01\x12b\n" +
	"\x11UpdateDeviceState\x12%.coordinator.UpdateDeviceStateRequest\x1a&.coordinator.UpdateDeviceStateResponseB9Z7protean-provider/pkg/protocol/coordinator;coordinatorpbb\x06proto3"

var (
	file_pkg_protocol_coordinator_coordinator_proto_rawDescOnce sync.Once
	file_pkg_protocol_coordinator_coordinator_proto_rawDescData []byte
)

func file_pkg_protocol_coordinator_coordinator_proto_rawDescGZIP() []byte {
	file_pkg_protocol_coordinator_coordinator_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_coordinator_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_coordinator_coordinator_proto_rawDesc), len(file_pkg_protocol_coordinator_coordinator_proto_rawDesc)))
	})
	return file_pkg_protocol_coordinator_coordinator_proto_rawDescData
}

var file_pkg_protocol_coordinator_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_protocol_coordinator_coordinator_proto_goTypes = []any{
	(*RegisterProviderRequest)(nil),   // 0: coordinator.RegisterProviderRequest
	(*RegisterProviderResponse)(nil),  // 1: coordinator.RegisterProviderResponse
	(*RegisterDeviceRequest)(nil),     // 2: coordinator.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),    // 3: coordinator.RegisterDeviceResponse
	(*ReleaseDeviceRequest)(nil),      // 4: coordinator.ReleaseDeviceRequest
	(*ReleaseDeviceResponse)(nil),     // 5: coordinator.ReleaseDeviceResponse
	(*UpdateDeviceStateRequest)(nil),  // 6: coordinator.UpdateDeviceStateRequest
	(*UpdateDeviceStateResponse)(nil), // 7: coordinator.UpdateDeviceStateResponse
	(*HeartbeatPing)(nil),             // 8: coordinator.HeartbeatPing
	(*HeartbeatPong)(nil),             // 9: coordinator.HeartbeatPong
	(*ReconnectCommand)(nil),          // 10: coordinator.ReconnectCommand
	(*ShutdownCommand)(nil),           // 11: coordinator.ShutdownCommand
	(*timestamp.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_pkg_protocol_coordinator_coordinator_proto_depIdxs = []int32{
	12, // 0: coordinator.RegisterDeviceRequest.connected_at:type_name -> google.protobuf.Timestamp
	12, // 1: coordinator.HeartbeatPing.sent_at:type_name -> google.protobuf.Timestamp
	12, // 2: coordinator.HeartbeatPong.received_at:type_name -> google.protobuf.Timestamp
	10, // 3: coordinator.HeartbeatPong.reconnect:type_name -> coordinator.ReconnectCommand
	11, // 4: coordinator.HeartbeatPong.shutdown:type_name -> coordinator.ShutdownCommand
	0,  // 5: coordinator.CoordinatorService.RegisterProvider:input_type -> coordinator.RegisterProviderRequest
	2,  // 6: coordinator.CoordinatorService.RegisterDevice:input_type -> coordinator.RegisterDeviceRequest
	4,  // 7: coordinator.CoordinatorService.ReleaseDevice:input_type -> coordinator.ReleaseDeviceRequest
	8,  // 8: coordinator.CoordinatorService.Heartbeat:input_type -> coordinator.HeartbeatPing
	6,  // 9: coordinator.CoordinatorService.UpdateDeviceState:input_type -> coordinator.UpdateDeviceStateRequest
	1,  // 10: coordinator.CoordinatorService.RegisterProvider:output_type -> coordinator.RegisterProviderResponse
	3,  // 11: coordinator.CoordinatorService.RegisterDevice:output_type -> coordinator.RegisterDeviceResponse
	5,  // 12: coordinator.CoordinatorService.ReleaseDevice:output_type -> coordinator.ReleaseDeviceResponse
	9,  // 13: coordinator.CoordinatorService.Heartbeat:output_type -> coordinator.HeartbeatPong
	7,  // 14: coordinator.CoordinatorService.UpdateDeviceState:output_type -> coordinator.UpdateDeviceStateResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_protocol_coordinator_coordinator_proto_init() }
func file_pkg_protocol_coordinator_coordinator_proto_init() {
	if File_pkg_protocol_coordinator_coordinator_proto != nil {
		return
	}
	file_pkg_protocol_coordinator_coordinator_proto_msgTypes[9].OneofWrappers = []any{
		(*HeartbeatPong_Reconnect)(nil),
		(*HeartbeatPong_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_coordinator_coordinator_proto_rawDesc), len(file_pkg_protocol_coordinator_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_coordinator_coordinator_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_coordinator_coordinator_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_coordinator_coordinator_proto_msgTypes,
	}.Build()
	File_pkg_protocol_coordinator_coordinator_proto = out.File
	file_pkg_protocol_coordinator_coordinator_proto_goTypes = nil
	file_pkg_protocol_coordinator_coordinator_proto_depIdxs = nil
}
